Comma separated part numbers for run-tests.py
emichael/dslabs pull request #66
Opened 2023-12-06 01:30 UTC by armanbm177

Enabled multiple part nums to be run in sequence for run-tests.py. Inspired by the lab 4 part 3 exploit, that doesn't require a working part 2 to get a majority of part 3 points. 

Example terminal commands:
./run-tests.py -l 4 -p 2,3

2023-12-06 02:04 UTC, emichael requested changes
Thanks for looking into this!

The only problem I can see is that this is incompatible with the `testNum` option. Look at `DSLabsTestCore:220`. I think you need to only allow non-fully-qualified test numbers when there is exactly one part specified.

That is `-l 1 -p 2 -n 4` should work, but `-l 1 -p 2,3 -n 4` should not.

The other possibility is for the second command to work and choose test 4 in parts 2 and 3, but I don't think you'd ever want to do that.

2023-12-06 02:04 UTC, emichael commented on handout-files/run-tests.py
> +    parser.add_argument('-p', '--part', type=str,
`str` is the default type, no need to specify it

Also, please make a note in the help string about what kinds of inputs this can take now. Look at `--test-num`

2023-12-11 06:39 UTC, wilcoxjay commented
> you need to only allow non-fully-qualified test numbers when there is exactly one part specified.
> 
> That is `-l 1 -p 2 -n 4` should work, but `-l 1 -p 2,3 -n 4` should not.

This makes sense to me. Is it ok to only put this check in the python script, or do we enforce these things in both python and java?

2023-12-13 20:42 UTC, emichael commented
Either/both is fine. There could be more input validation and better error messages for the student facing scripts in general :-)

2024-01-14 03:25 UTC, merged